# config.yml
# Configuración de Rasa para el sistema de verificación arquitectónica

version: "3.1"

assistant: "Verificación Arquitectónica Bot"

language: es

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

# Configuración de respuestas
responses:
  utter_greet:
  - text: "¡Hola! Soy tu asistente de verificación arquitectónica. ¿En qué puedo ayudarte?"
  
  utter_help:
  - text: "Puedo ayudarte con:\n- Verificación de documentos arquitectónicos\n- Análisis de cumplimiento normativo\n- Revisión de planos y memorias\n- Consultas sobre el CTE y normativas\n\n¿Qué necesitas verificar?"
  
  utter_goodbye:
  - text: "¡Hasta luego! Si necesitas más ayuda con tu proyecto arquitectónico, no dudes en preguntarme."
  
  utter_ask_project_type:
  - text: "¿Es un edificio existente o un proyecto nuevo? Esto me ayudará a aplicar las normativas correctas."
  
  utter_ask_documents:
  - text: "¿Qué documentos tienes disponibles? Por ejemplo: planos, memoria descriptiva, presupuesto, etc."
  
  utter_analysis_complete:
  - text: "He completado el análisis de tu proyecto. Los resultados están disponibles en el panel principal."
  
  utter_error:
  - text: "Lo siento, ha ocurrido un error. Por favor, inténtalo de nuevo o contacta con el administrador."

# Configuración de entidades
entities:
  - project_type
  - document_type
  - building_type
  - location

# Configuración de slots
slots:
  project_type:
    type: text
    mappings:
    - type: from_entity
      entity: project_type
  document_type:
    type: text
    mappings:
    - type: from_entity
      entity: document_type
  building_type:
    type: text
    mappings:
    - type: from_entity
      entity: building_type
  location:
    type: text
    mappings:
    - type: from_entity
      entity: location